version: '2'
services:
  app:
    build: .
    restart: always
    ports:
      - '8080:80'
      - '8081:8080'
#    volumes:
#      - './data:/data'

# docker-compose -f docker-compose.dev.yml up --build
